### ISSUE TITLE
Error while processing form response! (class java.lang.Integer cannot be cast to class java.lang.Boolean)

### ISSUE THREAD

**Issue by DxrkCxt** [GeyserMC/Cumulus#10]
(velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)
adoptium java 21
error: https://paste.gg/p/anonymous/77fd98a18918441bac7c4afbff5b886f/files/0c4f9a0d18bf42c291dac93eb02dce18/raw

**Comment by DxrkCxt** [comment]
I think this is because the wrong value was received in the packet.

**Comment by onebeastchris** [comment]
This would be an error in the Geyser implementation of the settings form; please open an issue on GeyserMC/geyser instead. Thanks!
