### ISSUE TITLE
Form suggestion: Store button click handler in ButtonComponent

### ISSUE THREAD

**Issue by maurxce** [GeyserMC/Cumulus#12]
SimpleForm:
Currently, there's a `SimpleForm.Builder#validResultHandler` that handles *all* buttons.
This can be very unclean when creating the buttons dynamically via a config (with predefined buttons).

Assume this is the current state:
```yaml
# config.yml
buttons:
  first:
    text: "Hello"
    url: "https://..."
  second:
    text: "World"
    utl: "https://..."
```
```java
ConfigurationSection buttons = config.getConfigurationSection("buttons");
if (buttons == null) return;

Map<String, Object> map = section.getValues(false);
SimpleForm.Builder builder = SimpleForm.builder();
```

Now with the requirements settled, let's look at how we currently have to manage button actions:
```java
AtomicReference<String> firstText = new AtomicReference<>("");
AtomicReference<String> secondText = new AtomicReference<>("");

map.forEach((key, value) -> {
    MemorySection section = (MemorySection) value;
    String text = section.getString("text");
    String url = section.getString("url");
	
    switch (key) {
        case "first" -> firstText.set(text);
        case "second" -> secondText.set(text);
    }
	
    form.button(text, FormImage.Type.URL, url);
});

form.validResultHandler(response -> {
    String text = response.clickedButton().text();
	
    if (text.equals(firstText.get())) {
        /* do something */
    }
	
    if (text.equals(secondText.get())) {
        /* do something else */
    }
});
```
As you can see, we need to use some global variables to manage the actions properly.
Now let's check out how it *could* be handled:
```java
map.forEach((key, value) -> {
    MemorySection section = (MemorySection) value;
    String text = section.getString("text");
    String url = section.getString("url");
	
    // no need for global variables
    form.button(text, FormImage.Type.URL, url, callback -> {
         switch (key) {
            case "first" -> /* do something */;
            case "second" -> /* do something else */;
        }
    });
})
```
As you can see, this method completely removes the need for globally accessible variables and even shortens the code

**Comment by maurxce** [comment]
My suggestion would not break any previous versions, by extending the `SimpleForm.java` interface with the following declarations:
```java
@This Builder button(@NonNull String text, FormImage.@NonNull Type type, @NonNull String data, Consumer<SimpleFormResponse> callback);
@This Builder button(@NonNull String text, @Nullable FormImage image, Consumer<SimpleFormResponse> callback);
@This Builder button(@NonNull String text, Consumer<SimpleFormResponse> callback);
```

**Comment by maurxce** [comment]
I have [cloned the repository and changed some things]( https://github.com/maurxce/Cumulus/compare/9fcceba...da65cd2):
- `ButtonComponent`
- `ButtonComponentImpl`
- `SimpleForm`
- `SimpleFormImpl`

I'm not too familiar with this repository, so I'm unsure on how to make it use the integrated callback yet.
Any help is greatly appreciated

**Comment by Tim203** [comment]
Hey, thanks for your suggestion!
I like that you also included an example.
I think that this is a good suggestion, because you can more easily use the context of the given element.
If others agree, this will be added in 2.0 which will be used in Geyser and Floodgate after the Geyser-Floodgate merge.

**Comment by Tim203** [comment]
Just like Floodgate 2.0, Floodgate 3.0 is taking much longer than I initially hoped and expected.
For the more technical people looking for this specific feature, Geyser already fully uses Cumulus 2.0 their features so you could just bump the dependency to Cumulus 2.0 and everything should just work on Geyser's side. So if you want to use this feature it should be relatively simple
